# Change these first
owner: raulredes # Your GitHub organization or username, where this repository lives
repo: funsadu # The name of this repository

sites:

  - name: Unanue
    check: "tcp-ping"
    url: unanue.funsadu.ar
    port: 60080
  - name: Cuchilloco
    check: "tcp-ping"
    url: cuchilloco.funsadu.ar
    port: 60080
  - name: Ceferino
    check: "tcp-ping"
    url: ceferino.funsadu.ar
    port: 60080
  - name: Aircontrol
    check: "tcp-ping"
    url: radios.funsadu.ar
    port: 9082
  - name: Gestion
    url: https://gestion.funsadu.ar/Radius/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: estado.funsadu.ar
  # baseUrl: /funsadu
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Estado de Funsadu
  introTitle: "**Estado** de los equipos "
  introMessage: Los equipos se monitorean cada 5 minutos, y se grafica el tiempo medio de respuesta
  navbar:
    - title: Status
      href: /
    - title: Gestion
      href: https://gestion.rpsa.ar/Radius/

# Upptime also supports notifications, assigning issues, and more
